### ISSUE TITLE
[Docker V2] Support private distribution repo

### ISSUE THREAD

**Issue by Skiepp** [Work-m8/backstage-docker-plugin#13]
This plugin can list docker images from DockerHub only.

It will be great to have it support private registries (non-docker hub) as well, which is the de-facto standandard for enterprise companies.

Documentation: https://distribution.github.io/distribution/spec/api/

Basically the api call changes from:
```/docker/v2/namespaces/${url.organization}/repositories/${url.repository}/tags```

To:
```/docker/v2/${image_name}/tags/list```

As for the authentication, it can be done by using an Oauth2 Bearer token, just like DockerHub

**Comment by pascalwilbrink** [comment]
Thank you for your request:)
I will take a look at it

**Comment by pascalwilbrink** [comment]
Hi @Skiepp,

can you try this version?
https://www.npmjs.com/package/@workm8/backstage-docker-tags/v/1.1.0-alpha

You can specify the `Registry` like following:


```
metadata:
  name: Grafana
  annotations:
    docker.com/repository: 'grafana/grafana'
    docker.com/registry: 'Docker'
```

Currently, you can choose between `Docker` and `GitHub` (Case sensitive).
